biolib_version: 2
modules:
    main:
        image: 'local-docker://equibind:latest'
        working_directory: /
        input_files:
            - COPY / /
        output_files:
            - COPY /output/ /
            - COPY /output.md /
        source_files: []
        gpu: required
arguments:
    -
        default_value: /input.zip
        description: 'Upload an input zip with the format found in the description: '
        key: '--input-zip'
        key_value_separator: ' '
        required: true
        type: file
    -   
        default_value: 'flex'
        description: 'Which pipeline to run for the docking'
        key: '--docking'
        key_value_separator: ' '
        type: multiselect
        required: False
        options:
            'Flexible self-docking': 'flex'
            'Rigid re-docking': 'rigid'        
main_output_file: /output.md
