biolib_version: 2

modules:
    main:
        image: 'local-docker://app-equibind:latest'
        command: ""
        input_files:
            - COPY / /input/
        output_files:
            - COPY /output/ /
            - COPY /output.md /
        source_files: []
        gpu: required

arguments:
    -
        default_value: /input.fa
        description: 'Enter sequence(s) in FASTA format: '
        key: '--fasta'
        key_value_separator: '='
        required: true
        type: text-file
        
main_output_file: /output.md


