biolib_version: 2
modules:
    main:
        image: 'local-docker://equibind:latest'
        command: "/run.sh"
        #working_directory: /home/biolib/
        input_files:
            - COPY / /
        output_files:
            - COPY /output/ /
            - COPY /output.md /
        source_files: []
        gpu: required
arguments:
    -
        default_value: /pdb.zip
        description: 'Upload a single file or a zip folder with the PDB protein files.'
        key: '--pdb'
        key_value_separator: ' '
        required: true
        type: file
    -
        default_value: /binder.zip
        description: 'Upload an single file or a zip folder with the binder files (.mol2 and .sdf formats)'
        key: '--binder'
        key_value_separator: ' '
        required: true
        type: file
    -   
        default_value: 'flex'
        description: 'Which pipeline to run for the docking'
        key: '--docking'
        key_value_separator: ' '
        type: multiselect
        required: False
        options:
            'Flexible self-docking': 'flex'
            'Rigid re-docking': 'rigid'        
main_output_file: /output.md
